---
- name: Spin up application at remote machine
  hosts: all
  tasks:
    - name: Shutdown ruuning application  
      shell:
        cmd: cd  /tmp/ && docker-compose down || true
  
    - name: Copy docker-compose.yml file to remote machine
      copy: 
        src:  docker-compose.yml 
        dest: /tmp/

    - name: Remove Previous Docker Images If Exists 
      shell:
        cmd: docker rmi pparth27743/telemedicine_webrtc_server  pparth27743/telemedicine_frontend  pparth27743/telemedicine_backend 2> /dev/null || true

    - name: Spin up application using docker-compose 
      shell:
        cmd: cd /tmp/ && docker-compose up -d  

